name: Run R analysis and save outputs

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual trigger from GitHub UI

jobs:
  r-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Install dependencies
        run: |
          R -e "install.packages(c('tidyverse', 'janitor', 'lubridate', 'scales'), repos='https://cloud.r-project.org')"

      - name: Run analysis script
        run: Rscript analysis.R

      - name: Upload cleaned CSV files
        uses: actions/upload-artifact@v4
        with:
          name: cleaned-data
          path: cleaned_data/
